export const TECNICAS_KIDS = [
  {
    modulo: "Fundamentos",
    nome: "Postura de luta em pé",
    faixa: "Branca",
    idadeMinima: 5,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 1,
  },
  {
    modulo: "Fundamentos",
    nome: "Base de defesa",
    faixa: "Branca",
    idadeMinima: 5,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 2,
  },
  {
    modulo: "Fundamentos",
    nome: "Rolamento para frente",
    faixa: "Branca",
    idadeMinima: 5,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 3,
  },
  {
    modulo: "Fundamentos",
    nome: "Rolamento para trás",
    faixa: "Branca",
    idadeMinima: 5,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 4,
  },
  {
    modulo: "Fundamentos",
    nome: "Pegada na gola e manga",
    faixa: "Branca",
    idadeMinima: 5,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 5,
  },
  {
    modulo: "Guarda",
    nome: "Puxada para guarda",
    faixa: "Branca",
    idadeMinima: 6,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 1,
  },
  {
    modulo: "Guarda",
    nome: "Fechar guarda",
    faixa: "Branca",
    idadeMinima: 5,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 2,
  },
  {
    modulo: "Guarda",
    nome: "Abrir guarda",
    faixa: "Cinza e Branca",
    idadeMinima: 6,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 3,
  },
  {
    modulo: "Raspagens",
    nome: "Raspagem simples",
    faixa: "Branca",
    idadeMinima: 6,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 1,
  },
  {
    modulo: "Raspagens",
    nome: "Raspagem tesoura",
    faixa: "Cinza e Branca",
    idadeMinima: 7,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 2,
  },
  {
    modulo: "Passagens",
    nome: "Passagem de guarda ajoelhado",
    faixa: "Cinza",
    idadeMinima: 7,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 1,
  },
  {
    modulo: "100kg",
    nome: "Controle dos 100kg",
    faixa: "Branca",
    idadeMinima: 6,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 1,
  },
  {
    modulo: "Montada",
    nome: "Estabilização da montada",
    faixa: "Cinza",
    idadeMinima: 7,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 1,
  },
  {
    modulo: "Costas",
    nome: "Controle das costas com ganchos",
    faixa: "Cinza e Preta",
    idadeMinima: 8,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 1,
  },
  {
    modulo: "Finalizações",
    nome: "Armlock da guarda",
    faixa: "Amarela e Branca",
    idadeMinima: 8,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 1,
  },
  {
    modulo: "Finalizações",
    nome: "Triângulo",
    faixa: "Amarela e Branca",
    idadeMinima: 8,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 2,
  },
  {
    modulo: "Finalizações",
    nome: "Omoplata",
    faixa: "Amarela",
    idadeMinima: 9,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 3,
  },
  {
    modulo: "Quedas",
    nome: "Queda de desequilíbrio simples",
    faixa: "Branca",
    idadeMinima: 6,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 1,
  },
  {
    modulo: "Competição",
    nome: "Noções de pontuação",
    faixa: "Branca",
    idadeMinima: 7,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 1,
  },
  {
    modulo: "Competição",
    nome: "Regras básicas",
    faixa: "Branca",
    idadeMinima: 7,
    idadeMaxima: 14,
    obrigatoria: true,
    ordem: 2,
  },
];